export default {
  LOAD_USER_INFO: "LOAD_USER_INFO",
  LOAD_USER_INFO_SUCCESS: "LOAD_USER_INFO_SUCCESS",
  LOAD_CART_PRODUCTS_ID_SUCCESS: "LOAD_CART_PRODUCTS_ID_SUCCESS",
  REQUEST_CART_PRODUCT_SUCCESS: "REQUEST_CART_PRODUCT_SUCCESS",
  REQUEST_INCREMENT_PRODUCT_QUANTITY: "REQUEST_INCREMENT_PRODUCT_QUANTITY",
  REQUEST_DECREMENT_PRODUCT_QUANTITY: "REQUEST_DECREMENT_PRODUCT_QUANTITY",
  FETCHING_PRODUCT_QUANTITY: "FETCHING_PRODUCT_QUANTITY",
  PRODUCT_QUANTITY_FETCH_DONE: "PRODUCT_QUANTITY_FETCH_DONE",
  SET_PRODUCT_PRICE: "SET_PRODUCT_PRICE"
};
